### ISSUE TITLE
Dodaj

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#14]
Dodaj to liczenie rankingu gildii:
Sumuje punkty każdego gracza w gildii a potem dzieli przez ilość tych członków..

**Comment by EastWestFM** [comment]
Znajduje się to w config.yml
Dokładniej opcja `config.algorithm.guild.points`.
`{MEMBERS_POINTS}` - suma punktów wszystkich członków.
`{MEMBERS_NUM}` - liczba członków gildii.

Podstawy matematyki :)
