### ISSUE TITLE
Nowe

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#15]
###### 

Dodaj jeszcze komende 

> /g efect - Losowy efekt dla gildii na okreslony czas(koszt tego i możliwośc właczenia  w configu)
> /g zycie - dodaje jedno życie do gildii( cene można ustawić w configu)
> /ga skarbiec |tag/nazwa| - sprawdza skarbiec danej gildii
> /ga lider |tag/nazwa|  |gracz| - przekazuje lidera gildii
> /ga pvp |tag/nazwa| - wlacza / wylacza pvp w gildii 
> /ga zycie |tag/nazwa| |set| |ilosc max 3|- ustawia życia dla gildii
> ###### 
> 
> Dodaj system last kill:
> Np. Jak gracz z nickiem "a" zabije gracza z nickiem "b" to dostanie np. "70" punktów, gdy drugi raz gracz "a" zabije gracza "b" dostenie "0" punktów a gdy np. zabije za drógim razem gracza "c" a potem "b" to za "b" normalnie dostaje ranking :)
> Krótko mówiąc żeby mnie było można nabijać rankingu :)
> ###### 
> 
> Dodaj tzw. Log blocka dla zalozyciela i lidera gildii :)
> ######

**Comment by EastWestFM** [comment]
Dodane w połowie :)
