### ISSUE TITLE
Dodatki / Zmiany

### ISSUE THREAD

**Issue by Reydann** [EastWestFM/RevoGuild#17]
Proponuje dodać / zmienić:
- Ustawianie ilość sojuszy
- Opłaty za sojusze
- Poprawnienie tabu aby było można używać tych samych ciągów znaków w slocie.
- Co 1 członek w gildii więcej, tym więcej trzeba zapłacić za dojście nowego.
- Dodać do tabu dużo więcej zmiennych, nazwa gracza, pkt graczy do rankingu obok itd. aby bardziej urozmaicić tab
- Zablokować wybrane komendy na cuboidzie gildii?
  Na razie tyle.

**Comment by EastWestFM** [comment]
Dodam w następnym update ;)

**Comment by TheMolkaPL** [comment]
Zapewne dzisiaj albo jutro :smile:.
Wiemy jak EW nolifi w Javie.

**Comment by EastWestFM** [comment]
No dzięki :(

**Comment by EastWestFM** [comment]
Opłata za sojusz ma być tylko dla gildii akceptującej sojusz? ;]

**Comment by Reydann** [comment]
Opłata ma być jednorazowa, oby dwie gildie płacą - do ustalenia w configu + czy opcja ma być on / off

**Comment by EastWestFM** [comment]
Dodałem tylko po stronie gildii akceptującej.
Wszystkie punkty zrealizowałem, zaraz wrzucę wersję na gita :)
