### ISSUE TITLE
Dodatek/zmiana

### ISSUE THREAD

**Issue by xW0LFx** [EastWestFM/RevoGuild#18]
DODAJ:
/g efekt - mozna uzywac co 1 dzien (Ponieważ spamic mozna tym ile wlezie ;p)
Blokowanie /sethome na terenie gildii

**Comment by TheMolkaPL** [comment]
Co do /sethome; może lepiej dodać do configu listę zablokowanych komend na terenie gildii.

**Comment by EastWestFM** [comment]
Efekt już poprawiłem, teraz biorę się za blokadę komend ;]

**Comment by EastWestFM** [comment]
Wsio dodane, testować! :)
