### ISSUE TITLE
Bug i to poważny!

### ISSUE THREAD

**Issue by xW0LFx** [EastWestFM/RevoGuild#21]
Po wyjsciu i wejsciu na serwer usuwa itemek w rece ;|

**Comment by kamcio96** [comment]
Jakie masz pluginy?

**Comment by xW0LFx** [comment]
kamcio96 to na 100% prze revoguild usuwałem wszystkie pl i wgrywałem pojedynczo i gdy wgrałem revo to usuwało ten itemek, wgrałem starsza wersje i działa.

**Comment by EastWestFM** [comment]
To revo bo mi się projekty podupczyły xD a jako, że jestem zajęty to nie mam czasu poprawić :game_die:

**Comment by kamcio96** [comment]
Ok, myslalem ze Istu nie popelnia takich bledow ;]

**Comment by EastWestFM** [comment]
MyHard wazniejszy, wybaczcie ;]
