### ISSUE TITLE
Błąd w bazie danych.

### ISSUE THREAD

**Issue by NotJustPizza** [EastWestFM/RevoGuild#22]
Plugin generuje nowym graczom dziwne wartość w polu zabójstw np. 406, 1102. Odkryłem to ponieważ tworzę system statystyk ze wsparciem dla RevoGuild.
![ss](https://cloud.githubusercontent.com/assets/9921307/5159813/9e4f1084-7374-11e4-949b-81cef280e62e.png)

**Comment by kamcio96** [comment]
na pewno wyswietlasz dobra kolumne z bazy? xD

**Comment by NotJustPizza** [comment]
```
$top = $this->db->query("SELECT lastNick, uuid, points, kills, deaths FROM ".MYSQL_PREFIX."users ORDER BY points LIMIT ".$max*2);
// (....)
echo $top[$c]->kills;
```

Nie ma mowy o pomyłce. Zapytanie jest poprawne i wyświetlam dobrą zmienną. 
P.S. Korzystam z wersji 4.1, bo 4.4 sypie błędami przy starcie. Coś nie tak z domyślną konfiguracją.

**Comment by EastWestFM** [comment]
Dziwnym cudem samo się to nadpisuje, gdzie nie wiem. ?Nie mam czasu na szuaknei bledu, myhard wazniejszy :D

**Comment by NotJustPizza** [comment]
Dobrze, zatem mój system porzuca support dla tego pluginu, bo nie będę wspierał kodu z tak druzgocącymi błędami. W sumie z drugiej strony będę miał więcej czasu by zająć się kodem dla FunnyGuilds i OpenGuild.
