### ISSUE TITLE
Obliczanie rankingu gildii

### ISSUE THREAD

**Issue by Sztandar18** [EastWestFM/RevoGuild#25]
Mam jeszcze jedno pytanie. Chciałem ranking gildii obliczać wg.
SUMA_PUNKTÓW_CZŁONKÓW/ILOŚĆ_CZŁONKÓW, a więc zrobiłem tak:
guild:
points: {MEMBERS_POINTS}/{MEMBERS_NUM}
Problem jest taki, że trzeba to zaokrąglić, ponieważ, na tabie wyświetla się coś w stylu:
[1260
drugiego nawiasu nie ma bo: wynik z tego obliczenia to liczba zmiennoprzecinkowa, a więc trzeba zaokrąglić, zrobiłem tak (nie mieści się na tabie):
Math.round({MEMBERS_POINTS}/{MEMBERS_NUM})
Niestety nie działa, za to fukcje Math w innych przypadkach np. przy obliczaniu rankingu gracza, zostały zastosowane w przykładowej konfiguracji i działają, co mam z tym zrobić?

**Comment by EastWestFM** [comment]
Jakiś log z konsoli ;_;

**Comment by Sztandar18** [comment]
Już wszystko ok, wszystko przez kolorki.
