### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by kukubaczek** [EastWestFM/RevoGuild#3]
Fajnie by było, gdyby można było (xd) ustawić algorytm w którym ustawialibysmy  koszt dołączenia do gildii w zależności od graczy w gildii.

**Comment by EastWestFM** [comment]
Sam o tym myślałem,  tylko będę musiał jakoś czarować,  bo nie mogę tego obrazu obliczać bo się sypie :G
Ale dodam na 100% :smile:

**Comment by EastWestFM** [comment]
Dodane ;)
