### ISSUE TITLE
config

### ISSUE THREAD

**Issue by kukubaczek** [EastWestFM/RevoGuild#4]
W configu so ustawienia co inni gracze mogą robić na terenie gildii. Np. Otwieranie skrzynek powinno być on, niszczenie bloków oczywiscie off itp.

Nie wiem czy to jest, ale jeszcze, żeby creeperowy wybuch niszczył teren gildii.

**Comment by EastWestFM** [comment]
Ok, dodam jak wrócę do domu ;)

**Comment by EastWestFM** [comment]
Połowicznie dodane ;)
