### ISSUE TITLE
Bład z UUID

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#5]
Caused by: java.lang.IllegalStateException: Cannot call getOfflinePlayer(UUID) on main thread, this operation is blocking!

**Comment by EastWestFM** [comment]
Używasz wersji 1.7.5, zalecam update na 1.7.9 ;)
W każdym bądź razie muszę to poprawić :/

**Comment by EastWestFM** [comment]
Dodano wsparcie nicków (**beta**) - opcja `config.useuuid` w konfiguracji ustawiona na `false` oznacza używanie nicków
