### ISSUE TITLE
g pvp

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#8]
Bład z g pvp jak zalozyciel wpisze tą komende to gracze z gildii za nie widzialni :/

**Comment by EastWestFM** [comment]
Tzn? Opisz dokładniej co się dzieje. Jaki tryb tagów nad głową masz wybrany? Podaj logi z konsoli.

**Comment by ghost** [comment]
Wybrany mam tagapi, Po prostu jak wpisuje /g pvp to znika ta osoba, która mialem w gildii i stała obok mnie... Ja jej nie widzę ale ona mnie widzi :)

**Comment by EastWestFM** [comment]
Tylko przy pvp? Usuwanie członków etc. działa ok? Podaj cały z konsoli ;)

**Comment by EastWestFM** [comment]
Rozwiązane, wina leżała po winie zmodyfikowanego klienta (cheaty) :dancer:
